# Meta
site_name: STPL
site_author: 'Joost van der Griendt'
site_url: ''

# Docs dir
docs_dir: '../docs'

# Repository
repo_name: 'BitBucket'
repo_url: 'https://p-bitbucket.nl.eu.abnamro.com:7999/scm/stpl/stpl-pipeline-core.git'

# Copyright
copyright: 'Copyright &copy; 2017 ABN AMRO B.V.'

# Theme
theme: 'material'

# Extra Options
extra:
  palette:
    primary: 'teal'
    accent: 'yellow'

# Extensions
markdown_extensions:
  - admonition
  - codehilite(linenums=true)
  - footnotes
  - meta
  - toc(permalink=true)
  - pymdownx.arithmatex
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.tilde

